# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(977, 740)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(977, 740))
        Form.setMaximumSize(QtCore.QSize(977, 740))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 981, 711))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpace = QtGui.QWidget()
        self.tabSpace.setObjectName(_fromUtf8("tabSpace"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabSpace)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 30, 761, 541))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layoutSpace = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutSpace.setObjectName(_fromUtf8("layoutSpace"))
        self.grpSpaceIlluminance = QtGui.QGroupBox(self.tabSpace)
        self.grpSpaceIlluminance.setGeometry(QtCore.QRect(0, 30, 201, 231))
        self.grpSpaceIlluminance.setToolTip(_fromUtf8(""))
        self.grpSpaceIlluminance.setObjectName(_fromUtf8("grpSpaceIlluminance"))
        self.groupSpaceNavigateIlluminance = QtGui.QGroupBox(self.grpSpaceIlluminance)
        self.groupSpaceNavigateIlluminance.setGeometry(QtCore.QRect(0, 40, 201, 191))
        self.groupSpaceNavigateIlluminance.setAutoFillBackground(False)
        self.groupSpaceNavigateIlluminance.setStyleSheet(_fromUtf8(""))
        self.groupSpaceNavigateIlluminance.setObjectName(_fromUtf8("groupSpaceNavigateIlluminance"))
        self.cmbSpaceTimeIllum = QtGui.QComboBox(self.groupSpaceNavigateIlluminance)
        self.cmbSpaceTimeIllum.setGeometry(QtCore.QRect(110, 30, 81, 21))
        self.cmbSpaceTimeIllum.setObjectName(_fromUtf8("cmbSpaceTimeIllum"))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.lblSpaceTime = QtGui.QLabel(self.groupSpaceNavigateIlluminance)
        self.lblSpaceTime.setGeometry(QtCore.QRect(130, 0, 31, 41))
        self.lblSpaceTime.setObjectName(_fromUtf8("lblSpaceTime"))
        self.calSpaceDateTimeIllum = QtGui.QDateTimeEdit(self.groupSpaceNavigateIlluminance)
        self.calSpaceDateTimeIllum.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.calSpaceDateTimeIllum.setWrapping(True)
        self.calSpaceDateTimeIllum.setAlignment(QtCore.Qt.AlignCenter)
        self.calSpaceDateTimeIllum.setDate(QtCore.QDate(2015, 1, 1))
        self.calSpaceDateTimeIllum.setTime(QtCore.QTime(0, 0, 0))
        self.calSpaceDateTimeIllum.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 12, 31), QtCore.QTime(23, 59, 59)))
        self.calSpaceDateTimeIllum.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.calSpaceDateTimeIllum.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.calSpaceDateTimeIllum.setCalendarPopup(True)
        self.calSpaceDateTimeIllum.setObjectName(_fromUtf8("calSpaceDateTimeIllum"))
        self.lblSpaceDate = QtGui.QLabel(self.groupSpaceNavigateIlluminance)
        self.lblSpaceDate.setGeometry(QtCore.QRect(40, 10, 31, 21))
        self.lblSpaceDate.setObjectName(_fromUtf8("lblSpaceDate"))
        self.grpSpaceIlluminanceNavigateDetailed = QtGui.QGroupBox(self.groupSpaceNavigateIlluminance)
        self.grpSpaceIlluminanceNavigateDetailed.setGeometry(QtCore.QRect(0, 60, 201, 131))
        self.grpSpaceIlluminanceNavigateDetailed.setTitle(_fromUtf8(""))
        self.grpSpaceIlluminanceNavigateDetailed.setObjectName(_fromUtf8("grpSpaceIlluminanceNavigateDetailed"))
        self.cmbSpaceTimeIntervalMin = QtGui.QComboBox(self.grpSpaceIlluminanceNavigateDetailed)
        self.cmbSpaceTimeIntervalMin.setGeometry(QtCore.QRect(42, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cmbSpaceTimeIntervalMin.setFont(font)
        self.cmbSpaceTimeIntervalMin.setObjectName(_fromUtf8("cmbSpaceTimeIntervalMin"))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.lblSpaceTimeStep = QtGui.QLabel(self.grpSpaceIlluminanceNavigateDetailed)
        self.lblSpaceTimeStep.setGeometry(QtCore.QRect(7, 100, 56, 20))
        self.lblSpaceTimeStep.setObjectName(_fromUtf8("lblSpaceTimeStep"))
        self.cmbSpaceIlluminanceStepType = QtGui.QComboBox(self.grpSpaceIlluminanceNavigateDetailed)
        self.cmbSpaceIlluminanceStepType.setGeometry(QtCore.QRect(69, 100, 55, 20))
        self.cmbSpaceIlluminanceStepType.setObjectName(_fromUtf8("cmbSpaceIlluminanceStepType"))
        self.cmbSpaceIlluminanceStepType.addItem(_fromUtf8(""))
        self.cmbSpaceIlluminanceStepType.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax = QtGui.QComboBox(self.grpSpaceIlluminanceNavigateDetailed)
        self.cmbSpaceTimeIntervalMax.setGeometry(QtCore.QRect(119, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cmbSpaceTimeIntervalMax.setFont(font)
        self.cmbSpaceTimeIntervalMax.setObjectName(_fromUtf8("cmbSpaceTimeIntervalMax"))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.chkSpaceSkipDarkHours = QtGui.QCheckBox(self.grpSpaceIlluminanceNavigateDetailed)
        self.chkSpaceSkipDarkHours.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.chkSpaceSkipDarkHours.setObjectName(_fromUtf8("chkSpaceSkipDarkHours"))
        self.lblSpaceDayInterval = QtGui.QLabel(self.grpSpaceIlluminanceNavigateDetailed)
        self.lblSpaceDayInterval.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.lblSpaceDayInterval.setObjectName(_fromUtf8("lblSpaceDayInterval"))
        self.cmbSpaceIluminanceStepValue = QtGui.QComboBox(self.grpSpaceIlluminanceNavigateDetailed)
        self.cmbSpaceIluminanceStepValue.setGeometry(QtCore.QRect(130, 100, 56, 20))
        self.cmbSpaceIluminanceStepValue.setObjectName(_fromUtf8("cmbSpaceIluminanceStepValue"))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.btnSpacePrevHour = QtGui.QPushButton(self.grpSpaceIlluminanceNavigateDetailed)
        self.btnSpacePrevHour.setGeometry(QtCore.QRect(10, 10, 88, 20))
        self.btnSpacePrevHour.setObjectName(_fromUtf8("btnSpacePrevHour"))
        self.btnSpaceNextHour = QtGui.QPushButton(self.grpSpaceIlluminanceNavigateDetailed)
        self.btnSpaceNextHour.setGeometry(QtCore.QRect(103, 10, 88, 20))
        self.btnSpaceNextHour.setObjectName(_fromUtf8("btnSpaceNextHour"))
        self.cmbSpaceSelectIlluminanceFile = QtGui.QComboBox(self.grpSpaceIlluminance)
        self.cmbSpaceSelectIlluminanceFile.setGeometry(QtCore.QRect(10, 20, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cmbSpaceSelectIlluminanceFile.setFont(font)
        self.cmbSpaceSelectIlluminanceFile.setObjectName(_fromUtf8("cmbSpaceSelectIlluminanceFile"))
        self.cmbSpacePlotType = QtGui.QComboBox(self.tabSpace)
        self.cmbSpacePlotType.setGeometry(QtCore.QRect(10, 2, 181, 21))
        self.cmbSpacePlotType.setObjectName(_fromUtf8("cmbSpacePlotType"))
        self.grpSpaceColorScheme = QtGui.QGroupBox(self.tabSpace)
        self.grpSpaceColorScheme.setGeometry(QtCore.QRect(0, 570, 201, 111))
        self.grpSpaceColorScheme.setTitle(_fromUtf8(""))
        self.grpSpaceColorScheme.setObjectName(_fromUtf8("grpSpaceColorScheme"))
        self.lblSpaceChartOpacity = QtGui.QLabel(self.grpSpaceColorScheme)
        self.lblSpaceChartOpacity.setGeometry(QtCore.QRect(11, 50, 121, 16))
        self.lblSpaceChartOpacity.setObjectName(_fromUtf8("lblSpaceChartOpacity"))
        self.txtSpaceOpacityValue = QtGui.QLineEdit(self.grpSpaceColorScheme)
        self.txtSpaceOpacityValue.setEnabled(False)
        self.txtSpaceOpacityValue.setGeometry(QtCore.QRect(160, 60, 31, 20))
        self.txtSpaceOpacityValue.setObjectName(_fromUtf8("txtSpaceOpacityValue"))
        self.sliderSpaceOpacity = QtGui.QSlider(self.grpSpaceColorScheme)
        self.sliderSpaceOpacity.setGeometry(QtCore.QRect(11, 60, 141, 20))
        self.sliderSpaceOpacity.setMaximum(100)
        self.sliderSpaceOpacity.setSliderPosition(100)
        self.sliderSpaceOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpaceOpacity.setObjectName(_fromUtf8("sliderSpaceOpacity"))
        self.lblSpaceColorSchemeSelect = QtGui.QLabel(self.grpSpaceColorScheme)
        self.lblSpaceColorSchemeSelect.setGeometry(QtCore.QRect(10, 0, 121, 16))
        self.lblSpaceColorSchemeSelect.setObjectName(_fromUtf8("lblSpaceColorSchemeSelect"))
        self.cmbSpaceColorScheme = QtGui.QComboBox(self.grpSpaceColorScheme)
        self.cmbSpaceColorScheme.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.cmbSpaceColorScheme.setObjectName(_fromUtf8("cmbSpaceColorScheme"))
        self.chkSpaceColorSchemeInvert = QtGui.QCheckBox(self.grpSpaceColorScheme)
        self.chkSpaceColorSchemeInvert.setGeometry(QtCore.QRect(150, 15, 51, 31))
        self.chkSpaceColorSchemeInvert.setObjectName(_fromUtf8("chkSpaceColorSchemeInvert"))
        self.btnSpaceSetColorScheme = QtGui.QPushButton(self.grpSpaceColorScheme)
        self.btnSpaceSetColorScheme.setGeometry(QtCore.QRect(10, 82, 181, 21))
        self.btnSpaceSetColorScheme.setObjectName(_fromUtf8("btnSpaceSetColorScheme"))
        self.txtSpaceMsgBox = QtGui.QTextBrowser(self.tabSpace)
        self.txtSpaceMsgBox.setGeometry(QtCore.QRect(610, 580, 361, 101))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtSpaceMsgBox.setFont(font)
        self.txtSpaceMsgBox.setStyleSheet(_fromUtf8(""))
        self.txtSpaceMsgBox.setObjectName(_fromUtf8("txtSpaceMsgBox"))
        self.txtSpaceStatusDisplay = QtGui.QLineEdit(self.tabSpace)
        self.txtSpaceStatusDisplay.setEnabled(False)
        self.txtSpaceStatusDisplay.setGeometry(QtCore.QRect(210, 2, 761, 21))
        self.txtSpaceStatusDisplay.setObjectName(_fromUtf8("txtSpaceStatusDisplay"))
        self.grpSpaceColorContourSettings = QtGui.QGroupBox(self.tabSpace)
        self.grpSpaceColorContourSettings.setGeometry(QtCore.QRect(0, 260, 201, 311))
        self.grpSpaceColorContourSettings.setTitle(_fromUtf8(""))
        self.grpSpaceColorContourSettings.setObjectName(_fromUtf8("grpSpaceColorContourSettings"))
        self.grpColoursIlluminance = QtGui.QGroupBox(self.grpSpaceColorContourSettings)
        self.grpColoursIlluminance.setGeometry(QtCore.QRect(110, 50, 81, 261))
        self.grpColoursIlluminance.setStyleSheet(_fromUtf8(""))
        self.grpColoursIlluminance.setTitle(_fromUtf8(""))
        self.grpColoursIlluminance.setObjectName(_fromUtf8("grpColoursIlluminance"))
        self.btnSelectColorLowerMask = QtGui.QPushButton(self.grpColoursIlluminance)
        self.btnSelectColorLowerMask.setGeometry(QtCore.QRect(0, 190, 81, 21))
        self.btnSelectColorLowerMask.setObjectName(_fromUtf8("btnSelectColorLowerMask"))
        self.lblSpaceColorMinLimit = QtGui.QLabel(self.grpColoursIlluminance)
        self.lblSpaceColorMinLimit.setGeometry(QtCore.QRect(0, 70, 81, 20))
        self.lblSpaceColorMinLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSpaceColorMinLimit.setObjectName(_fromUtf8("lblSpaceColorMinLimit"))
        self.txtSpaceColorsMin = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtSpaceColorsMin.setGeometry(QtCore.QRect(0, 90, 81, 20))
        self.txtSpaceColorsMin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtSpaceColorsMin.setInputMask(_fromUtf8(""))
        self.txtSpaceColorsMin.setText(_fromUtf8(""))
        self.txtSpaceColorsMin.setCursorPosition(0)
        self.txtSpaceColorsMin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceColorsMin.setObjectName(_fromUtf8("txtSpaceColorsMin"))
        self.btnSelectColorUpperMask = QtGui.QPushButton(self.grpColoursIlluminance)
        self.btnSelectColorUpperMask.setGeometry(QtCore.QRect(0, 130, 81, 21))
        self.btnSelectColorUpperMask.setObjectName(_fromUtf8("btnSelectColorUpperMask"))
        self.txtSpaceColorsMax = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtSpaceColorsMax.setGeometry(QtCore.QRect(0, 40, 81, 20))
        self.txtSpaceColorsMax.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtSpaceColorsMax.setInputMask(_fromUtf8(""))
        self.txtSpaceColorsMax.setText(_fromUtf8(""))
        self.txtSpaceColorsMax.setCursorPosition(0)
        self.txtSpaceColorsMax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceColorsMax.setObjectName(_fromUtf8("txtSpaceColorsMax"))
        self.lblSpaceColorMaxLimit = QtGui.QLabel(self.grpColoursIlluminance)
        self.lblSpaceColorMaxLimit.setGeometry(QtCore.QRect(0, 20, 81, 20))
        self.lblSpaceColorMaxLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSpaceColorMaxLimit.setObjectName(_fromUtf8("lblSpaceColorMaxLimit"))
        self.txtSpaceColorsUpperMask = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtSpaceColorsUpperMask.setEnabled(False)
        self.txtSpaceColorsUpperMask.setGeometry(QtCore.QRect(0, 150, 81, 20))
        self.txtSpaceColorsUpperMask.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtSpaceColorsUpperMask.setInputMask(_fromUtf8(""))
        self.txtSpaceColorsUpperMask.setCursorPosition(0)
        self.txtSpaceColorsUpperMask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceColorsUpperMask.setObjectName(_fromUtf8("txtSpaceColorsUpperMask"))
        self.txtSpaceColorsLowerMask = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtSpaceColorsLowerMask.setEnabled(False)
        self.txtSpaceColorsLowerMask.setGeometry(QtCore.QRect(0, 210, 81, 20))
        self.txtSpaceColorsLowerMask.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtSpaceColorsLowerMask.setInputMask(_fromUtf8(""))
        self.txtSpaceColorsLowerMask.setCursorPosition(0)
        self.txtSpaceColorsLowerMask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceColorsLowerMask.setObjectName(_fromUtf8("txtSpaceColorsLowerMask"))
        self.btnSpaceSetColors = QtGui.QPushButton(self.grpColoursIlluminance)
        self.btnSpaceSetColors.setGeometry(QtCore.QRect(0, 240, 79, 19))
        self.btnSpaceSetColors.setObjectName(_fromUtf8("btnSpaceSetColors"))
        self.btnSpaceResetColors = QtGui.QPushButton(self.grpColoursIlluminance)
        self.btnSpaceResetColors.setGeometry(QtCore.QRect(0, 1, 79, 18))
        self.btnSpaceResetColors.setObjectName(_fromUtf8("btnSpaceResetColors"))
        self.chkSpaceContours = QtGui.QCheckBox(self.grpSpaceColorContourSettings)
        self.chkSpaceContours.setGeometry(QtCore.QRect(10, 0, 81, 20))
        self.chkSpaceContours.setChecked(True)
        self.chkSpaceContours.setObjectName(_fromUtf8("chkSpaceContours"))
        self.grpContoursIlluminance = QtGui.QGroupBox(self.grpSpaceColorContourSettings)
        self.grpContoursIlluminance.setGeometry(QtCore.QRect(10, 50, 81, 261))
        self.grpContoursIlluminance.setTitle(_fromUtf8(""))
        self.grpContoursIlluminance.setObjectName(_fromUtf8("grpContoursIlluminance"))
        self.btnSpaceSetContours = QtGui.QPushButton(self.grpContoursIlluminance)
        self.btnSpaceSetContours.setGeometry(QtCore.QRect(0, 240, 79, 19))
        self.btnSpaceSetContours.setObjectName(_fromUtf8("btnSpaceSetContours"))
        self.txtSpaceCountourValue6 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue6.setGeometry(QtCore.QRect(0, 166, 79, 18))
        self.txtSpaceCountourValue6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue6.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue6.setCursorPosition(0)
        self.txtSpaceCountourValue6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue6.setObjectName(_fromUtf8("txtSpaceCountourValue6"))
        self.btnSpaceResetContours = QtGui.QPushButton(self.grpContoursIlluminance)
        self.btnSpaceResetContours.setGeometry(QtCore.QRect(0, 1, 79, 18))
        self.btnSpaceResetContours.setObjectName(_fromUtf8("btnSpaceResetContours"))
        self.txtSpaceCountourValue7 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue7.setGeometry(QtCore.QRect(0, 190, 79, 17))
        self.txtSpaceCountourValue7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue7.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue7.setCursorPosition(0)
        self.txtSpaceCountourValue7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue7.setObjectName(_fromUtf8("txtSpaceCountourValue7"))
        self.txtSpaceCountourValue5 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue5.setGeometry(QtCore.QRect(0, 143, 79, 17))
        self.txtSpaceCountourValue5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue5.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue5.setCursorPosition(0)
        self.txtSpaceCountourValue5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue5.setObjectName(_fromUtf8("txtSpaceCountourValue5"))
        self.txtSpaceCountourValue4 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue4.setGeometry(QtCore.QRect(0, 119, 79, 18))
        self.txtSpaceCountourValue4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue4.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue4.setCursorPosition(0)
        self.txtSpaceCountourValue4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue4.setObjectName(_fromUtf8("txtSpaceCountourValue4"))
        self.txtSpaceCountourValue1 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue1.setGeometry(QtCore.QRect(0, 49, 79, 17))
        self.txtSpaceCountourValue1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtSpaceCountourValue1.setAutoFillBackground(True)
        self.txtSpaceCountourValue1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue1.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue1.setCursorPosition(0)
        self.txtSpaceCountourValue1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue1.setObjectName(_fromUtf8("txtSpaceCountourValue1"))
        self.txtSpaceCountourValue2 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue2.setGeometry(QtCore.QRect(0, 72, 79, 18))
        self.txtSpaceCountourValue2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue2.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue2.setObjectName(_fromUtf8("txtSpaceCountourValue2"))
        self.txtSpaceCountourValue3 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue3.setGeometry(QtCore.QRect(0, 96, 79, 17))
        self.txtSpaceCountourValue3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue3.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue3.setCursorPosition(0)
        self.txtSpaceCountourValue3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue3.setObjectName(_fromUtf8("txtSpaceCountourValue3"))
        self.cmbSpaceContourQuantity = QtGui.QComboBox(self.grpContoursIlluminance)
        self.cmbSpaceContourQuantity.setGeometry(QtCore.QRect(0, 25, 79, 18))
        self.cmbSpaceContourQuantity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbSpaceContourQuantity.setObjectName(_fromUtf8("cmbSpaceContourQuantity"))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.txtSpaceCountourValue8 = QtGui.QLineEdit(self.grpContoursIlluminance)
        self.txtSpaceCountourValue8.setGeometry(QtCore.QRect(0, 214, 79, 17))
        self.txtSpaceCountourValue8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue8.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue8.setCursorPosition(0)
        self.txtSpaceCountourValue8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue8.setObjectName(_fromUtf8("txtSpaceCountourValue8"))
        self.btnSpaceSettingsColours = QtGui.QPushButton(self.grpSpaceColorContourSettings)
        self.btnSpaceSettingsColours.setGeometry(QtCore.QRect(110, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnSpaceSettingsColours.setFont(font)
        self.btnSpaceSettingsColours.setObjectName(_fromUtf8("btnSpaceSettingsColours"))
        self.btnSpaceSettingsContour = QtGui.QPushButton(self.grpSpaceColorContourSettings)
        self.btnSpaceSettingsContour.setEnabled(False)
        self.btnSpaceSettingsContour.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnSpaceSettingsContour.setFont(font)
        self.btnSpaceSettingsContour.setObjectName(_fromUtf8("btnSpaceSettingsContour"))
        self.chkSpaceColors = QtGui.QCheckBox(self.grpSpaceColorContourSettings)
        self.chkSpaceColors.setGeometry(QtCore.QRect(110, 0, 81, 20))
        self.chkSpaceColors.setChecked(True)
        self.chkSpaceColors.setObjectName(_fromUtf8("chkSpaceColors"))
        self.tabWidget.addTab(self.tabSpace, _fromUtf8(""))
        self.tabTimeSeries = QtGui.QWidget()
        self.tabTimeSeries.setObjectName(_fromUtf8("tabTimeSeries"))
        self.grpTimeSeriesMain = QtGui.QGroupBox(self.tabTimeSeries)
        self.grpTimeSeriesMain.setGeometry(QtCore.QRect(0, 0, 971, 691))
        self.grpTimeSeriesMain.setTitle(_fromUtf8(""))
        self.grpTimeSeriesMain.setObjectName(_fromUtf8("grpTimeSeriesMain"))
        self.cmbTimeSeriesPlotType = QtGui.QComboBox(self.grpTimeSeriesMain)
        self.cmbTimeSeriesPlotType.setGeometry(QtCore.QRect(10, 2, 181, 21))
        self.cmbTimeSeriesPlotType.setObjectName(_fromUtf8("cmbTimeSeriesPlotType"))
        self.grpTimeSeriesColorScheme = QtGui.QGroupBox(self.grpTimeSeriesMain)
        self.grpTimeSeriesColorScheme.setGeometry(QtCore.QRect(0, 570, 201, 111))
        self.grpTimeSeriesColorScheme.setTitle(_fromUtf8(""))
        self.grpTimeSeriesColorScheme.setObjectName(_fromUtf8("grpTimeSeriesColorScheme"))
        self.lblTimeSeriesChartOpacity = QtGui.QLabel(self.grpTimeSeriesColorScheme)
        self.lblTimeSeriesChartOpacity.setGeometry(QtCore.QRect(11, 50, 121, 16))
        self.lblTimeSeriesChartOpacity.setObjectName(_fromUtf8("lblTimeSeriesChartOpacity"))
        self.txtTimeSeriesOpacityValue = QtGui.QLineEdit(self.grpTimeSeriesColorScheme)
        self.txtTimeSeriesOpacityValue.setEnabled(False)
        self.txtTimeSeriesOpacityValue.setGeometry(QtCore.QRect(160, 60, 31, 20))
        self.txtTimeSeriesOpacityValue.setObjectName(_fromUtf8("txtTimeSeriesOpacityValue"))
        self.sliderTimeSeriesOpacity = QtGui.QSlider(self.grpTimeSeriesColorScheme)
        self.sliderTimeSeriesOpacity.setGeometry(QtCore.QRect(11, 60, 141, 20))
        self.sliderTimeSeriesOpacity.setMaximum(100)
        self.sliderTimeSeriesOpacity.setSliderPosition(100)
        self.sliderTimeSeriesOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTimeSeriesOpacity.setObjectName(_fromUtf8("sliderTimeSeriesOpacity"))
        self.lblTimeSeriesColorSchemeSelect = QtGui.QLabel(self.grpTimeSeriesColorScheme)
        self.lblTimeSeriesColorSchemeSelect.setGeometry(QtCore.QRect(10, 0, 121, 16))
        self.lblTimeSeriesColorSchemeSelect.setObjectName(_fromUtf8("lblTimeSeriesColorSchemeSelect"))
        self.cmbTimeSeriesColorScheme = QtGui.QComboBox(self.grpTimeSeriesColorScheme)
        self.cmbTimeSeriesColorScheme.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.cmbTimeSeriesColorScheme.setObjectName(_fromUtf8("cmbTimeSeriesColorScheme"))
        self.chkTimeSeriesColorSchemeInvert = QtGui.QCheckBox(self.grpTimeSeriesColorScheme)
        self.chkTimeSeriesColorSchemeInvert.setGeometry(QtCore.QRect(150, 15, 51, 31))
        self.chkTimeSeriesColorSchemeInvert.setObjectName(_fromUtf8("chkTimeSeriesColorSchemeInvert"))
        self.btnTimeSeriesSetColorScheme = QtGui.QPushButton(self.grpTimeSeriesColorScheme)
        self.btnTimeSeriesSetColorScheme.setGeometry(QtCore.QRect(10, 82, 181, 21))
        self.btnTimeSeriesSetColorScheme.setObjectName(_fromUtf8("btnTimeSeriesSetColorScheme"))
        self.txtTimeSeriesMsgBox = QtGui.QTextBrowser(self.grpTimeSeriesMain)
        self.txtTimeSeriesMsgBox.setGeometry(QtCore.QRect(610, 580, 361, 101))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.txtTimeSeriesMsgBox.setFont(font)
        self.txtTimeSeriesMsgBox.setStyleSheet(_fromUtf8(""))
        self.txtTimeSeriesMsgBox.setObjectName(_fromUtf8("txtTimeSeriesMsgBox"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.grpTimeSeriesMain)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 30, 761, 411))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.layoutTimeSeries = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layoutTimeSeries.setObjectName(_fromUtf8("layoutTimeSeries"))
        self.txtTimeSeriesStatusDisplay = QtGui.QLineEdit(self.tabTimeSeries)
        self.txtTimeSeriesStatusDisplay.setEnabled(False)
        self.txtTimeSeriesStatusDisplay.setGeometry(QtCore.QRect(210, 2, 761, 21))
        self.txtTimeSeriesStatusDisplay.setObjectName(_fromUtf8("txtTimeSeriesStatusDisplay"))
        self.tabWidget.addTab(self.tabTimeSeries, _fromUtf8(""))
        self.grpFileDialog = QtGui.QGroupBox(Form)
        self.grpFileDialog.setEnabled(True)
        self.grpFileDialog.setGeometry(QtCore.QRect(-10, -10, 981, 41))
        self.grpFileDialog.setTitle(_fromUtf8(""))
        self.grpFileDialog.setObjectName(_fromUtf8("grpFileDialog"))
        self.btnOpenJson = QtGui.QPushButton(self.grpFileDialog)
        self.btnOpenJson.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.btnOpenJson.setObjectName(_fromUtf8("btnOpenJson"))
        self.txtJsonPath = QtGui.QLineEdit(self.grpFileDialog)
        self.txtJsonPath.setEnabled(False)
        self.txtJsonPath.setGeometry(QtCore.QRect(120, 10, 511, 23))
        self.txtJsonPath.setReadOnly(False)
        self.txtJsonPath.setObjectName(_fromUtf8("txtJsonPath"))
        self.cmbSpaceName = QtGui.QComboBox(self.grpFileDialog)
        self.cmbSpaceName.setEnabled(False)
        self.cmbSpaceName.setGeometry(QtCore.QRect(710, 10, 161, 23))
        self.cmbSpaceName.setObjectName(_fromUtf8("cmbSpaceName"))
        self.btnSelectSpaceName = QtGui.QPushButton(self.grpFileDialog)
        self.btnSelectSpaceName.setEnabled(False)
        self.btnSelectSpaceName.setGeometry(QtCore.QRect(890, 10, 91, 23))
        self.btnSelectSpaceName.setObjectName(_fromUtf8("btnSelectSpaceName"))
        self.lblSpaceName = QtGui.QLabel(self.grpFileDialog)
        self.lblSpaceName.setGeometry(QtCore.QRect(660, 10, 46, 23))
        self.lblSpaceName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSpaceName.setObjectName(_fromUtf8("lblSpaceName"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.cmbSpaceTimeIllum.setCurrentIndex(8)
        self.cmbSpaceTimeIntervalMin.setCurrentIndex(8)
        self.cmbSpaceTimeIntervalMax.setCurrentIndex(8)
        self.cmbSpaceContourQuantity.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cmbSpacePlotType, self.cmbSpaceSelectIlluminanceFile)
        Form.setTabOrder(self.cmbSpaceSelectIlluminanceFile, self.calSpaceDateTimeIllum)
        Form.setTabOrder(self.calSpaceDateTimeIllum, self.cmbSpaceTimeIllum)
        Form.setTabOrder(self.cmbSpaceTimeIllum, self.chkSpaceContours)
        Form.setTabOrder(self.chkSpaceContours, self.btnSpaceSettingsContour)
        Form.setTabOrder(self.btnSpaceSettingsContour, self.chkSpaceColors)
        Form.setTabOrder(self.chkSpaceColors, self.btnSpaceSettingsColours)
        Form.setTabOrder(self.btnSpaceSettingsColours, self.btnSpaceSetContours)
        Form.setTabOrder(self.btnSpaceSetContours, self.btnSpaceResetColors)
        Form.setTabOrder(self.btnSpaceResetColors, self.txtSpaceColorsMax)
        Form.setTabOrder(self.txtSpaceColorsMax, self.txtSpaceColorsMin)
        Form.setTabOrder(self.txtSpaceColorsMin, self.btnSelectColorUpperMask)
        Form.setTabOrder(self.btnSelectColorUpperMask, self.txtSpaceColorsUpperMask)
        Form.setTabOrder(self.txtSpaceColorsUpperMask, self.btnSelectColorLowerMask)
        Form.setTabOrder(self.btnSelectColorLowerMask, self.txtSpaceColorsLowerMask)
        Form.setTabOrder(self.txtSpaceColorsLowerMask, self.btnSpaceSetColors)
        Form.setTabOrder(self.btnSpaceSetColors, self.cmbSpaceColorScheme)
        Form.setTabOrder(self.cmbSpaceColorScheme, self.chkSpaceColorSchemeInvert)
        Form.setTabOrder(self.chkSpaceColorSchemeInvert, self.sliderSpaceOpacity)
        Form.setTabOrder(self.sliderSpaceOpacity, self.txtSpaceOpacityValue)
        Form.setTabOrder(self.txtSpaceOpacityValue, self.btnSpaceSetColorScheme)
        Form.setTabOrder(self.btnSpaceSetColorScheme, self.txtJsonPath)
        Form.setTabOrder(self.txtJsonPath, self.cmbSpaceName)
        Form.setTabOrder(self.cmbSpaceName, self.btnOpenJson)
        Form.setTabOrder(self.btnOpenJson, self.tabWidget)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "STADICvis 0.01", None))
        self.grpSpaceIlluminance.setTitle(_translate("Form", "Illuminance Settings", None))
        self.groupSpaceNavigateIlluminance.setToolTip(_translate("Form", "The navigation settings can be used to view plots corresponding to different dates and hours.", None))
        self.groupSpaceNavigateIlluminance.setTitle(_translate("Form", "Navigate", None))
        self.cmbSpaceTimeIllum.setToolTip(_translate("Form", "Select a time for which the data is to be displayed.", None))
        self.cmbSpaceTimeIllum.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceTimeIllum.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceTimeIllum.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceTimeIllum.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceTimeIllum.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceTimeIllum.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceTimeIllum.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceTimeIllum.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceTimeIllum.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceTimeIllum.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceTimeIllum.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceTimeIllum.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceTimeIllum.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceTimeIllum.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceTimeIllum.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceTimeIllum.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceTimeIllum.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceTimeIllum.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceTimeIllum.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceTimeIllum.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceTimeIllum.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceTimeIllum.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceTimeIllum.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceTimeIllum.setItemText(23, _translate("Form", "24", None))
        self.lblSpaceTime.setText(_translate("Form", "Time", None))
        self.calSpaceDateTimeIllum.setToolTip(_translate("Form", "Select a date by clicking on the pop-up calendar. Please note that selecting a year has no bearing on the data being displayed.", None))
        self.calSpaceDateTimeIllum.setDisplayFormat(_translate("Form", "MMMM/d", None))
        self.lblSpaceDate.setText(_translate("Form", "Date", None))
        self.cmbSpaceTimeIntervalMin.setToolTip(_translate("Form", "The interval settings, both inclusive, can be used to specify the time intervals for which the data is to be shown.", None))
        self.cmbSpaceTimeIntervalMin.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceTimeIntervalMin.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceTimeIntervalMin.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceTimeIntervalMin.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceTimeIntervalMin.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceTimeIntervalMin.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceTimeIntervalMin.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceTimeIntervalMin.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceTimeIntervalMin.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceTimeIntervalMin.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceTimeIntervalMin.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceTimeIntervalMin.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceTimeIntervalMin.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceTimeIntervalMin.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceTimeIntervalMin.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceTimeIntervalMin.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceTimeIntervalMin.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceTimeIntervalMin.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceTimeIntervalMin.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceTimeIntervalMin.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceTimeIntervalMin.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceTimeIntervalMin.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceTimeIntervalMin.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceTimeIntervalMin.setItemText(23, _translate("Form", "24", None))
        self.lblSpaceTimeStep.setToolTip(_translate("Form", "The Time Step settings can be used to specify a time step for navigating between different plots.", None))
        self.lblSpaceTimeStep.setText(_translate("Form", "Time Step", None))
        self.cmbSpaceIlluminanceStepType.setToolTip(_translate("Form", "Choose between an hour or day.", None))
        self.cmbSpaceIlluminanceStepType.setItemText(0, _translate("Form", "Hour", None))
        self.cmbSpaceIlluminanceStepType.setItemText(1, _translate("Form", "Day", None))
        self.cmbSpaceTimeIntervalMax.setToolTip(_translate("Form", "The interval settings, both inclusive, can be used to specify the time intervals for which the data is to be shown.", None))
        self.cmbSpaceTimeIntervalMax.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceTimeIntervalMax.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceTimeIntervalMax.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceTimeIntervalMax.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceTimeIntervalMax.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceTimeIntervalMax.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceTimeIntervalMax.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceTimeIntervalMax.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceTimeIntervalMax.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceTimeIntervalMax.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceTimeIntervalMax.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceTimeIntervalMax.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceTimeIntervalMax.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceTimeIntervalMax.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceTimeIntervalMax.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceTimeIntervalMax.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceTimeIntervalMax.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceTimeIntervalMax.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceTimeIntervalMax.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceTimeIntervalMax.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceTimeIntervalMax.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceTimeIntervalMax.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceTimeIntervalMax.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceTimeIntervalMax.setItemText(23, _translate("Form", "24", None))
        self.chkSpaceSkipDarkHours.setToolTip(_translate("Form", "Check this to skip over hours for which illuminance at every grid point is zero.", None))
        self.chkSpaceSkipDarkHours.setText(_translate("Form", "Skip dark hours", None))
        self.lblSpaceDayInterval.setToolTip(_translate("Form", "The interval settings, both inclusive, can be used to specify the time intervals for which the data is to be shown.", None))
        self.lblSpaceDayInterval.setText(_translate("Form", "Intvl", None))
        self.cmbSpaceIluminanceStepValue.setToolTip(_translate("Form", "Choose a multiplier for the timestep.", None))
        self.cmbSpaceIluminanceStepValue.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceIluminanceStepValue.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceIluminanceStepValue.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceIluminanceStepValue.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceIluminanceStepValue.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceIluminanceStepValue.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceIluminanceStepValue.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceIluminanceStepValue.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceIluminanceStepValue.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceIluminanceStepValue.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceIluminanceStepValue.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceIluminanceStepValue.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceIluminanceStepValue.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceIluminanceStepValue.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceIluminanceStepValue.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceIluminanceStepValue.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceIluminanceStepValue.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceIluminanceStepValue.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceIluminanceStepValue.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceIluminanceStepValue.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceIluminanceStepValue.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceIluminanceStepValue.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceIluminanceStepValue.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceIluminanceStepValue.setItemText(23, _translate("Form", "24", None))
        self.btnSpacePrevHour.setToolTip(_translate("Form", "Click to plot the previous hour/day as per the options specified in the controls below.", None))
        self.btnSpacePrevHour.setText(_translate("Form", "Previous", None))
        self.btnSpaceNextHour.setToolTip(_translate("Form", "Click to plot the next hour/day as per the options specified in the controls below.", None))
        self.btnSpaceNextHour.setText(_translate("Form", "Next", None))
        self.cmbSpaceSelectIlluminanceFile.setToolTip(_translate("Form", "<html><head/><body><p>Select the annual illuminance data that is to be plotted. The data selected by default is from the final illuminance file.</p></body></html>", None))
        self.cmbSpacePlotType.setToolTip(_translate("Form", "Select the type of data that you wish to plot", None))
        self.lblSpaceChartOpacity.setToolTip(_translate("Form", "Select an opacity for the colors in the chart by using the slider.", None))
        self.lblSpaceChartOpacity.setText(_translate("Form", "Select Chart Opacity", None))
        self.txtSpaceOpacityValue.setPlaceholderText(_translate("Form", "100", None))
        self.sliderSpaceOpacity.setToolTip(_translate("Form", "Select an opacity for the colors in the chart by using the slider.", None))
        self.lblSpaceColorSchemeSelect.setText(_translate("Form", "Color Scheme", None))
        self.cmbSpaceColorScheme.setToolTip(_translate("Form", "Select a color scheme for the chart.", None))
        self.chkSpaceColorSchemeInvert.setToolTip(_translate("Form", "Check this box to invert the selected color scheme.", None))
        self.chkSpaceColorSchemeInvert.setText(_translate("Form", "Invert", None))
        self.btnSpaceSetColorScheme.setToolTip(_translate("Form", "Click to confirm the Color Scheme and Opacity settings.", None))
        self.btnSpaceSetColorScheme.setText(_translate("Form", "Confirm", None))
        self.txtSpaceMsgBox.setToolTip(_translate("Form", "This text panel displays data pertaining to visualizations and file paths which might be helpful in troubleshooting errors.", None))
        self.btnSelectColorLowerMask.setToolTip(_translate("Form", "This option can be used to assign a specifc color to grid points which are lesser than the value specified in the text box below.", None))
        self.btnSelectColorLowerMask.setText(_translate("Form", "Lower Mask", None))
        self.lblSpaceColorMinLimit.setToolTip(_translate("Form", "The minimum limit specifies the lowest value for the color grid.", None))
        self.lblSpaceColorMinLimit.setText(_translate("Form", "Minimum Limit", None))
        self.txtSpaceColorsMin.setToolTip(_translate("Form", "The minimum limit specifies the lowest value for the color grid.", None))
        self.btnSelectColorUpperMask.setToolTip(_translate("Form", "This option can be used to assign a specifc color to grid points which are greater than the value specified in the text box below.", None))
        self.btnSelectColorUpperMask.setText(_translate("Form", "Upper Mask", None))
        self.txtSpaceColorsMax.setToolTip(_translate("Form", "The maximum limit specifies the highest value for the color grid.", None))
        self.lblSpaceColorMaxLimit.setToolTip(_translate("Form", "The maximum limit specifies the highest value for the color grid.", None))
        self.lblSpaceColorMaxLimit.setText(_translate("Form", "Maximum Limit", None))
        self.txtSpaceColorsUpperMask.setToolTip(_translate("Form", "Enter a positive number. The value of the upper mask should be always higher than the lower mask.", None))
        self.txtSpaceColorsLowerMask.setToolTip(_translate("Form", "Enter a positive number. The value of the upper mask should be always higher than the lower mask.", None))
        self.btnSpaceSetColors.setToolTip(_translate("Form", "Click to confirm the color settings.", None))
        self.btnSpaceSetColors.setText(_translate("Form", "Confirm", None))
        self.btnSpaceResetColors.setToolTip(_translate("Form", "Click to reset the color settings to their default values.", None))
        self.btnSpaceResetColors.setText(_translate("Form", "Reset", None))
        self.chkSpaceContours.setToolTip(_translate("Form", "Click to toggle between contour display on the chart.", None))
        self.chkSpaceContours.setText(_translate("Form", "Contours", None))
        self.btnSpaceSetContours.setToolTip(_translate("Form", "Click to confirm the contour settings.", None))
        self.btnSpaceSetContours.setText(_translate("Form", "Confirm", None))
        self.txtSpaceCountourValue6.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.btnSpaceResetContours.setToolTip(_translate("Form", "Click to reset the contour settings to their default values.", None))
        self.btnSpaceResetContours.setText(_translate("Form", "Reset", None))
        self.txtSpaceCountourValue7.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.txtSpaceCountourValue5.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.txtSpaceCountourValue4.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.txtSpaceCountourValue1.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.txtSpaceCountourValue2.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.txtSpaceCountourValue3.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.cmbSpaceContourQuantity.setToolTip(_translate("Form", "Select the number of contour lines on the plot.", None))
        self.cmbSpaceContourQuantity.setItemText(0, _translate("Form", "2", None))
        self.cmbSpaceContourQuantity.setItemText(1, _translate("Form", "3", None))
        self.cmbSpaceContourQuantity.setItemText(2, _translate("Form", "4", None))
        self.cmbSpaceContourQuantity.setItemText(3, _translate("Form", "5", None))
        self.cmbSpaceContourQuantity.setItemText(4, _translate("Form", "6", None))
        self.cmbSpaceContourQuantity.setItemText(5, _translate("Form", "7", None))
        self.cmbSpaceContourQuantity.setItemText(6, _translate("Form", "8", None))
        self.txtSpaceCountourValue8.setToolTip(_translate("Form", "Enter a positive number to set a contour line.", None))
        self.btnSpaceSettingsColours.setToolTip(_translate("Form", "Click to show further settings.", None))
        self.btnSpaceSettingsColours.setText(_translate("Form", "Show Settings", None))
        self.btnSpaceSettingsContour.setToolTip(_translate("Form", "Click to show further settings.", None))
        self.btnSpaceSettingsContour.setText(_translate("Form", "Show Settings", None))
        self.chkSpaceColors.setToolTip(_translate("Form", "Click to toggle between display of colored grids on the plot.", None))
        self.chkSpaceColors.setText(_translate("Form", "Colors", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpace), _translate("Form", "Spatial Plots", None))
        self.cmbTimeSeriesPlotType.setToolTip(_translate("Form", "Select the type of data that you wish to plot", None))
        self.lblTimeSeriesChartOpacity.setToolTip(_translate("Form", "Select an opacity for the colors in the chart by using the slider.", None))
        self.lblTimeSeriesChartOpacity.setText(_translate("Form", "Select Chart Opacity", None))
        self.txtTimeSeriesOpacityValue.setPlaceholderText(_translate("Form", "100", None))
        self.sliderTimeSeriesOpacity.setToolTip(_translate("Form", "Select an opacity for the colors in the chart by using the slider.", None))
        self.lblTimeSeriesColorSchemeSelect.setText(_translate("Form", "Color Scheme", None))
        self.cmbTimeSeriesColorScheme.setToolTip(_translate("Form", "Select a color scheme for the chart.", None))
        self.chkTimeSeriesColorSchemeInvert.setToolTip(_translate("Form", "Check this box to invert the selected color scheme.", None))
        self.chkTimeSeriesColorSchemeInvert.setText(_translate("Form", "Invert", None))
        self.btnTimeSeriesSetColorScheme.setToolTip(_translate("Form", "Click to confirm the Color Scheme and Opacity settings.", None))
        self.btnTimeSeriesSetColorScheme.setText(_translate("Form", "Confirm", None))
        self.txtTimeSeriesMsgBox.setToolTip(_translate("Form", "This text panel displays data pertaining to visualizations and file paths which might be helpful in troubleshooting errors.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTimeSeries), _translate("Form", "Time Series Plots", None))
        self.btnOpenJson.setText(_translate("Form", "Open Json File", None))
        self.btnSelectSpaceName.setText(_translate("Form", "Confirm", None))
        self.lblSpaceName.setText(_translate("Form", "Space", None))

