# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1091, 813)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 1091, 761))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpace = QtGui.QWidget()
        self.tabSpace.setObjectName(_fromUtf8("tabSpace"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabSpace)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 0, 871, 731))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layoutIlluminance = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutIlluminance.setObjectName(_fromUtf8("layoutIlluminance"))
        self.grpSpaceIlluminance = QtGui.QGroupBox(self.tabSpace)
        self.grpSpaceIlluminance.setGeometry(QtCore.QRect(0, 30, 201, 581))
        self.grpSpaceIlluminance.setToolTip(_fromUtf8(""))
        self.grpSpaceIlluminance.setObjectName(_fromUtf8("grpSpaceIlluminance"))
        self.chkSpaceContours = QtGui.QCheckBox(self.grpSpaceIlluminance)
        self.chkSpaceContours.setGeometry(QtCore.QRect(10, 270, 81, 20))
        self.chkSpaceContours.setChecked(True)
        self.chkSpaceContours.setObjectName(_fromUtf8("chkSpaceContours"))
        self.btnSpaceSettingsContour = QtGui.QPushButton(self.grpSpaceIlluminance)
        self.btnSpaceSettingsContour.setGeometry(QtCore.QRect(10, 290, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnSpaceSettingsContour.setFont(font)
        self.btnSpaceSettingsContour.setObjectName(_fromUtf8("btnSpaceSettingsContour"))
        self.groupSpaceNavigateIlluminance = QtGui.QGroupBox(self.grpSpaceIlluminance)
        self.groupSpaceNavigateIlluminance.setGeometry(QtCore.QRect(0, 70, 201, 191))
        self.groupSpaceNavigateIlluminance.setAutoFillBackground(False)
        self.groupSpaceNavigateIlluminance.setStyleSheet(_fromUtf8(""))
        self.groupSpaceNavigateIlluminance.setObjectName(_fromUtf8("groupSpaceNavigateIlluminance"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupSpaceNavigateIlluminance)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 181, 25))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.layoutSpacePreviousNextHours = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutSpacePreviousNextHours.setObjectName(_fromUtf8("layoutSpacePreviousNextHours"))
        self.btnSpacePrevHour = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnSpacePrevHour.setObjectName(_fromUtf8("btnSpacePrevHour"))
        self.layoutSpacePreviousNextHours.addWidget(self.btnSpacePrevHour)
        self.btnSpaceNextHour = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnSpaceNextHour.setObjectName(_fromUtf8("btnSpaceNextHour"))
        self.layoutSpacePreviousNextHours.addWidget(self.btnSpaceNextHour)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupSpaceNavigateIlluminance)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 181, 22))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.layoutSpaceTimeInterval = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutSpaceTimeInterval.setObjectName(_fromUtf8("layoutSpaceTimeInterval"))
        self.lblSpaceDayInterval = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.lblSpaceDayInterval.setObjectName(_fromUtf8("lblSpaceDayInterval"))
        self.layoutSpaceTimeInterval.addWidget(self.lblSpaceDayInterval)
        self.cmbSpaceTimeIntervalMin = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.cmbSpaceTimeIntervalMin.setObjectName(_fromUtf8("cmbSpaceTimeIntervalMin"))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMin.addItem(_fromUtf8(""))
        self.layoutSpaceTimeInterval.addWidget(self.cmbSpaceTimeIntervalMin)
        self.cmbSpaceTimeIntervalMax = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.cmbSpaceTimeIntervalMax.setObjectName(_fromUtf8("cmbSpaceTimeIntervalMax"))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIntervalMax.addItem(_fromUtf8(""))
        self.layoutSpaceTimeInterval.addWidget(self.cmbSpaceTimeIntervalMax)
        self.chkSpaceSkipDarkHours = QtGui.QCheckBox(self.groupSpaceNavigateIlluminance)
        self.chkSpaceSkipDarkHours.setGeometry(QtCore.QRect(10, 130, 181, 20))
        self.chkSpaceSkipDarkHours.setObjectName(_fromUtf8("chkSpaceSkipDarkHours"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupSpaceNavigateIlluminance)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 181, 22))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.layoutSpaceIlluminanceStep = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.layoutSpaceIlluminanceStep.setObjectName(_fromUtf8("layoutSpaceIlluminanceStep"))
        self.lblSpaceTimeStep = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.lblSpaceTimeStep.setObjectName(_fromUtf8("lblSpaceTimeStep"))
        self.layoutSpaceIlluminanceStep.addWidget(self.lblSpaceTimeStep)
        self.cmbSpaceIlluminanceStepType = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.cmbSpaceIlluminanceStepType.setObjectName(_fromUtf8("cmbSpaceIlluminanceStepType"))
        self.cmbSpaceIlluminanceStepType.addItem(_fromUtf8(""))
        self.cmbSpaceIlluminanceStepType.addItem(_fromUtf8(""))
        self.layoutSpaceIlluminanceStep.addWidget(self.cmbSpaceIlluminanceStepType)
        self.cmbSpaceIluminanceStepValue = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.cmbSpaceIluminanceStepValue.setObjectName(_fromUtf8("cmbSpaceIluminanceStepValue"))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.cmbSpaceIluminanceStepValue.addItem(_fromUtf8(""))
        self.layoutSpaceIlluminanceStep.addWidget(self.cmbSpaceIluminanceStepValue)
        self.cmbSpaceTimeIllum = QtGui.QComboBox(self.groupSpaceNavigateIlluminance)
        self.cmbSpaceTimeIllum.setGeometry(QtCore.QRect(110, 30, 81, 21))
        self.cmbSpaceTimeIllum.setObjectName(_fromUtf8("cmbSpaceTimeIllum"))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.cmbSpaceTimeIllum.addItem(_fromUtf8(""))
        self.lblSpaceTime = QtGui.QLabel(self.groupSpaceNavigateIlluminance)
        self.lblSpaceTime.setGeometry(QtCore.QRect(130, 0, 31, 41))
        self.lblSpaceTime.setObjectName(_fromUtf8("lblSpaceTime"))
        self.calSpaceDateTimeIllum = QtGui.QDateTimeEdit(self.groupSpaceNavigateIlluminance)
        self.calSpaceDateTimeIllum.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.calSpaceDateTimeIllum.setWrapping(True)
        self.calSpaceDateTimeIllum.setAlignment(QtCore.Qt.AlignCenter)
        self.calSpaceDateTimeIllum.setDate(QtCore.QDate(2015, 1, 1))
        self.calSpaceDateTimeIllum.setTime(QtCore.QTime(0, 0, 0))
        self.calSpaceDateTimeIllum.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 12, 31), QtCore.QTime(23, 59, 59)))
        self.calSpaceDateTimeIllum.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.calSpaceDateTimeIllum.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.calSpaceDateTimeIllum.setCalendarPopup(True)
        self.calSpaceDateTimeIllum.setObjectName(_fromUtf8("calSpaceDateTimeIllum"))
        self.lblSpaceDate = QtGui.QLabel(self.groupSpaceNavigateIlluminance)
        self.lblSpaceDate.setGeometry(QtCore.QRect(40, 10, 31, 21))
        self.lblSpaceDate.setObjectName(_fromUtf8("lblSpaceDate"))
        self.btnSpaceSettingsColours = QtGui.QPushButton(self.grpSpaceIlluminance)
        self.btnSpaceSettingsColours.setGeometry(QtCore.QRect(110, 290, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnSpaceSettingsColours.setFont(font)
        self.btnSpaceSettingsColours.setObjectName(_fromUtf8("btnSpaceSettingsColours"))
        self.chkSpaceColors = QtGui.QCheckBox(self.grpSpaceIlluminance)
        self.chkSpaceColors.setGeometry(QtCore.QRect(110, 270, 81, 20))
        self.chkSpaceColors.setChecked(True)
        self.chkSpaceColors.setObjectName(_fromUtf8("chkSpaceColors"))
        self.grpColoursIlluminance = QtGui.QGroupBox(self.grpSpaceIlluminance)
        self.grpColoursIlluminance.setGeometry(QtCore.QRect(110, 320, 81, 251))
        self.grpColoursIlluminance.setStyleSheet(_fromUtf8(""))
        self.grpColoursIlluminance.setTitle(_fromUtf8(""))
        self.grpColoursIlluminance.setObjectName(_fromUtf8("grpColoursIlluminance"))
        self.btnSelectColorLowerMask = QtGui.QPushButton(self.grpColoursIlluminance)
        self.btnSelectColorLowerMask.setGeometry(QtCore.QRect(0, 210, 81, 21))
        self.btnSelectColorLowerMask.setObjectName(_fromUtf8("btnSelectColorLowerMask"))
        self.lblColorMinLimit = QtGui.QLabel(self.grpColoursIlluminance)
        self.lblColorMinLimit.setGeometry(QtCore.QRect(0, 40, 81, 20))
        self.lblColorMinLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColorMinLimit.setObjectName(_fromUtf8("lblColorMinLimit"))
        self.txtColorsMin = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtColorsMin.setGeometry(QtCore.QRect(0, 60, 81, 20))
        self.txtColorsMin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtColorsMin.setCursorPosition(0)
        self.txtColorsMin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtColorsMin.setObjectName(_fromUtf8("txtColorsMin"))
        self.btnSelectColorUpperMask = QtGui.QPushButton(self.grpColoursIlluminance)
        self.btnSelectColorUpperMask.setGeometry(QtCore.QRect(0, 130, 81, 21))
        self.btnSelectColorUpperMask.setObjectName(_fromUtf8("btnSelectColorUpperMask"))
        self.txtColorsMax = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtColorsMax.setGeometry(QtCore.QRect(0, 20, 81, 20))
        self.txtColorsMax.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtColorsMax.setCursorPosition(0)
        self.txtColorsMax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtColorsMax.setObjectName(_fromUtf8("txtColorsMax"))
        self.lblColorUpperMask = QtGui.QLabel(self.grpColoursIlluminance)
        self.lblColorUpperMask.setGeometry(QtCore.QRect(0, 90, 81, 20))
        self.lblColorUpperMask.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColorUpperMask.setObjectName(_fromUtf8("lblColorUpperMask"))
        self.lblColorMaxLimit = QtGui.QLabel(self.grpColoursIlluminance)
        self.lblColorMaxLimit.setGeometry(QtCore.QRect(0, 0, 81, 20))
        self.lblColorMaxLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColorMaxLimit.setObjectName(_fromUtf8("lblColorMaxLimit"))
        self.lblColorLowerMask = QtGui.QLabel(self.grpColoursIlluminance)
        self.lblColorLowerMask.setGeometry(QtCore.QRect(0, 170, 81, 20))
        self.lblColorLowerMask.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColorLowerMask.setObjectName(_fromUtf8("lblColorLowerMask"))
        self.txtColorsUpperMask = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtColorsUpperMask.setGeometry(QtCore.QRect(0, 110, 81, 20))
        self.txtColorsUpperMask.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtColorsUpperMask.setCursorPosition(0)
        self.txtColorsUpperMask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtColorsUpperMask.setObjectName(_fromUtf8("txtColorsUpperMask"))
        self.txtColorsLowerMask = QtGui.QLineEdit(self.grpColoursIlluminance)
        self.txtColorsLowerMask.setGeometry(QtCore.QRect(0, 190, 81, 20))
        self.txtColorsLowerMask.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtColorsLowerMask.setCursorPosition(0)
        self.txtColorsLowerMask.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtColorsLowerMask.setObjectName(_fromUtf8("txtColorsLowerMask"))
        self.grpContoursIlluminance = QtGui.QGroupBox(self.grpSpaceIlluminance)
        self.grpContoursIlluminance.setGeometry(QtCore.QRect(10, 320, 81, 231))
        self.grpContoursIlluminance.setTitle(_fromUtf8(""))
        self.grpContoursIlluminance.setObjectName(_fromUtf8("grpContoursIlluminance"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.grpSpaceIlluminance)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 81, 285))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.layoutSpaceContourSettings = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layoutSpaceContourSettings.setObjectName(_fromUtf8("layoutSpaceContourSettings"))
        self.cmbSpaceContourQuantity = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cmbSpaceContourQuantity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbSpaceContourQuantity.setObjectName(_fromUtf8("cmbSpaceContourQuantity"))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.cmbSpaceContourQuantity.addItem(_fromUtf8(""))
        self.layoutSpaceContourSettings.addWidget(self.cmbSpaceContourQuantity)
        self.btnSpaceResetContours = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btnSpaceResetContours.setObjectName(_fromUtf8("btnSpaceResetContours"))
        self.layoutSpaceContourSettings.addWidget(self.btnSpaceResetContours)
        self.txtSpaceCountourValue1 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtSpaceCountourValue1.setAutoFillBackground(True)
        self.txtSpaceCountourValue1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue1.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue1.setCursorPosition(0)
        self.txtSpaceCountourValue1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue1.setObjectName(_fromUtf8("txtSpaceCountourValue1"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue1)
        self.txtSpaceCountourValue2 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue2.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue2.setObjectName(_fromUtf8("txtSpaceCountourValue2"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue2)
        self.txtSpaceCountourValue3 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue3.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue3.setCursorPosition(0)
        self.txtSpaceCountourValue3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue3.setObjectName(_fromUtf8("txtSpaceCountourValue3"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue3)
        self.txtSpaceCountourValue4 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue4.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue4.setCursorPosition(0)
        self.txtSpaceCountourValue4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue4.setObjectName(_fromUtf8("txtSpaceCountourValue4"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue4)
        self.txtSpaceCountourValue5 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue5.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue5.setCursorPosition(0)
        self.txtSpaceCountourValue5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue5.setObjectName(_fromUtf8("txtSpaceCountourValue5"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue5)
        self.txtSpaceCountourValue6 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue6.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue6.setCursorPosition(0)
        self.txtSpaceCountourValue6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue6.setObjectName(_fromUtf8("txtSpaceCountourValue6"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue6)
        self.txtSpaceCountourValue7 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.txtSpaceCountourValue7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtSpaceCountourValue7.setInputMask(_fromUtf8(""))
        self.txtSpaceCountourValue7.setCursorPosition(0)
        self.txtSpaceCountourValue7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtSpaceCountourValue7.setObjectName(_fromUtf8("txtSpaceCountourValue7"))
        self.layoutSpaceContourSettings.addWidget(self.txtSpaceCountourValue7)
        self.btnSpaceSetContours = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btnSpaceSetContours.setObjectName(_fromUtf8("btnSpaceSetContours"))
        self.layoutSpaceContourSettings.addWidget(self.btnSpaceSetContours)
        self.chkSpaceAutoFillContours = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.chkSpaceAutoFillContours.setChecked(True)
        self.chkSpaceAutoFillContours.setObjectName(_fromUtf8("chkSpaceAutoFillContours"))
        self.layoutSpaceContourSettings.addWidget(self.chkSpaceAutoFillContours)
        self.cmbSpaceSelectIlluminanceFile = QtGui.QComboBox(self.grpSpaceIlluminance)
        self.cmbSpaceSelectIlluminanceFile.setGeometry(QtCore.QRect(10, 20, 181, 22))
        self.cmbSpaceSelectIlluminanceFile.setObjectName(_fromUtf8("cmbSpaceSelectIlluminanceFile"))
        self.btnSapceSelectFileTypeIlluminance = QtGui.QPushButton(self.grpSpaceIlluminance)
        self.btnSapceSelectFileTypeIlluminance.setGeometry(QtCore.QRect(60, 43, 75, 21))
        self.btnSapceSelectFileTypeIlluminance.setObjectName(_fromUtf8("btnSapceSelectFileTypeIlluminance"))
        self.cmbSpacePlotType = QtGui.QComboBox(self.tabSpace)
        self.cmbSpacePlotType.setGeometry(QtCore.QRect(10, 2, 181, 21))
        self.cmbSpacePlotType.setObjectName(_fromUtf8("cmbSpacePlotType"))
        self.grpSpaceColorScheme = QtGui.QGroupBox(self.tabSpace)
        self.grpSpaceColorScheme.setGeometry(QtCore.QRect(0, 620, 201, 111))
        self.grpSpaceColorScheme.setTitle(_fromUtf8(""))
        self.grpSpaceColorScheme.setObjectName(_fromUtf8("grpSpaceColorScheme"))
        self.lblSpaceChartOpacity = QtGui.QLabel(self.grpSpaceColorScheme)
        self.lblSpaceChartOpacity.setGeometry(QtCore.QRect(11, 50, 121, 16))
        self.lblSpaceChartOpacity.setObjectName(_fromUtf8("lblSpaceChartOpacity"))
        self.txtSpaceOpacityValue = QtGui.QLineEdit(self.grpSpaceColorScheme)
        self.txtSpaceOpacityValue.setEnabled(False)
        self.txtSpaceOpacityValue.setGeometry(QtCore.QRect(160, 60, 31, 20))
        self.txtSpaceOpacityValue.setObjectName(_fromUtf8("txtSpaceOpacityValue"))
        self.sliderSpaceOpacity = QtGui.QSlider(self.grpSpaceColorScheme)
        self.sliderSpaceOpacity.setGeometry(QtCore.QRect(11, 60, 141, 20))
        self.sliderSpaceOpacity.setMaximum(100)
        self.sliderSpaceOpacity.setSliderPosition(100)
        self.sliderSpaceOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpaceOpacity.setObjectName(_fromUtf8("sliderSpaceOpacity"))
        self.lblSpaceColorSchemeSelect = QtGui.QLabel(self.grpSpaceColorScheme)
        self.lblSpaceColorSchemeSelect.setGeometry(QtCore.QRect(10, 5, 121, 16))
        self.lblSpaceColorSchemeSelect.setObjectName(_fromUtf8("lblSpaceColorSchemeSelect"))
        self.cmbSpaceColorScheme = QtGui.QComboBox(self.grpSpaceColorScheme)
        self.cmbSpaceColorScheme.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.cmbSpaceColorScheme.setObjectName(_fromUtf8("cmbSpaceColorScheme"))
        self.chkSpaceColorSchemeInvert = QtGui.QCheckBox(self.grpSpaceColorScheme)
        self.chkSpaceColorSchemeInvert.setGeometry(QtCore.QRect(150, 15, 51, 31))
        self.chkSpaceColorSchemeInvert.setObjectName(_fromUtf8("chkSpaceColorSchemeInvert"))
        self.btnSpaceSetColorScheme = QtGui.QPushButton(self.grpSpaceColorScheme)
        self.btnSpaceSetColorScheme.setGeometry(QtCore.QRect(10, 82, 181, 21))
        self.btnSpaceSetColorScheme.setObjectName(_fromUtf8("btnSpaceSetColorScheme"))
        self.tabWidget.addTab(self.tabSpace, _fromUtf8(""))
        self.tabTimeSeries = QtGui.QWidget()
        self.tabTimeSeries.setObjectName(_fromUtf8("tabTimeSeries"))
        self.tabWidget.addTab(self.tabTimeSeries, _fromUtf8(""))
        self.grpFileDialog = QtGui.QGroupBox(Form)
        self.grpFileDialog.setEnabled(False)
        self.grpFileDialog.setGeometry(QtCore.QRect(-10, -10, 1101, 61))
        self.grpFileDialog.setObjectName(_fromUtf8("grpFileDialog"))
        self.btnOpenJson = QtGui.QPushButton(self.grpFileDialog)
        self.btnOpenJson.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.btnOpenJson.setObjectName(_fromUtf8("btnOpenJson"))
        self.txtJsonPath = QtGui.QLineEdit(self.grpFileDialog)
        self.txtJsonPath.setEnabled(False)
        self.txtJsonPath.setGeometry(QtCore.QRect(130, 10, 931, 20))
        self.txtJsonPath.setReadOnly(False)
        self.txtJsonPath.setObjectName(_fromUtf8("txtJsonPath"))
        self.comboBox = QtGui.QComboBox(self.grpFileDialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 69, 16))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.cmbSpaceTimeIntervalMin.setCurrentIndex(8)
        self.cmbSpaceTimeIntervalMax.setCurrentIndex(8)
        self.cmbSpaceTimeIllum.setCurrentIndex(8)
        self.cmbSpaceContourQuantity.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.btnOpenJson)
        Form.setTabOrder(self.btnOpenJson, self.txtJsonPath)
        Form.setTabOrder(self.txtJsonPath, self.comboBox)
        Form.setTabOrder(self.comboBox, self.cmbSpacePlotType)
        Form.setTabOrder(self.cmbSpacePlotType, self.btnSpacePrevHour)
        Form.setTabOrder(self.btnSpacePrevHour, self.btnSpaceNextHour)
        Form.setTabOrder(self.btnSpaceNextHour, self.cmbSpaceTimeIntervalMin)
        Form.setTabOrder(self.cmbSpaceTimeIntervalMin, self.cmbSpaceTimeIntervalMax)
        Form.setTabOrder(self.cmbSpaceTimeIntervalMax, self.cmbSpaceIlluminanceStepType)
        Form.setTabOrder(self.cmbSpaceIlluminanceStepType, self.cmbSpaceIluminanceStepValue)
        Form.setTabOrder(self.cmbSpaceIluminanceStepValue, self.chkSpaceContours)
        Form.setTabOrder(self.chkSpaceContours, self.chkSpaceColors)
        Form.setTabOrder(self.chkSpaceColors, self.btnSpaceSettingsContour)
        Form.setTabOrder(self.btnSpaceSettingsContour, self.cmbSpaceContourQuantity)
        Form.setTabOrder(self.cmbSpaceContourQuantity, self.btnSpaceResetContours)
        Form.setTabOrder(self.btnSpaceResetContours, self.txtSpaceCountourValue1)
        Form.setTabOrder(self.txtSpaceCountourValue1, self.txtSpaceCountourValue2)
        Form.setTabOrder(self.txtSpaceCountourValue2, self.txtSpaceCountourValue3)
        Form.setTabOrder(self.txtSpaceCountourValue3, self.txtSpaceCountourValue4)
        Form.setTabOrder(self.txtSpaceCountourValue4, self.txtSpaceCountourValue5)
        Form.setTabOrder(self.txtSpaceCountourValue5, self.txtSpaceCountourValue6)
        Form.setTabOrder(self.txtSpaceCountourValue6, self.txtSpaceCountourValue7)
        Form.setTabOrder(self.txtSpaceCountourValue7, self.btnSpaceSetContours)
        Form.setTabOrder(self.btnSpaceSetContours, self.chkSpaceAutoFillContours)
        Form.setTabOrder(self.chkSpaceAutoFillContours, self.btnSpaceSettingsColours)
        Form.setTabOrder(self.btnSpaceSettingsColours, self.txtColorsMax)
        Form.setTabOrder(self.txtColorsMax, self.txtColorsMin)
        Form.setTabOrder(self.txtColorsMin, self.txtColorsUpperMask)
        Form.setTabOrder(self.txtColorsUpperMask, self.btnSelectColorUpperMask)
        Form.setTabOrder(self.btnSelectColorUpperMask, self.txtColorsLowerMask)
        Form.setTabOrder(self.txtColorsLowerMask, self.btnSelectColorLowerMask)
        Form.setTabOrder(self.btnSelectColorLowerMask, self.chkSpaceSkipDarkHours)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "STADICvis", None))
        self.grpSpaceIlluminance.setTitle(_translate("Form", "Illuminance Settings", None))
        self.chkSpaceContours.setText(_translate("Form", "Contours", None))
        self.btnSpaceSettingsContour.setText(_translate("Form", "Show Settings", None))
        self.groupSpaceNavigateIlluminance.setTitle(_translate("Form", "Navigate", None))
        self.btnSpacePrevHour.setText(_translate("Form", "Previous", None))
        self.btnSpaceNextHour.setText(_translate("Form", "Next", None))
        self.lblSpaceDayInterval.setText(_translate("Form", "Interval", None))
        self.cmbSpaceTimeIntervalMin.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceTimeIntervalMin.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceTimeIntervalMin.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceTimeIntervalMin.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceTimeIntervalMin.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceTimeIntervalMin.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceTimeIntervalMin.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceTimeIntervalMin.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceTimeIntervalMin.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceTimeIntervalMin.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceTimeIntervalMin.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceTimeIntervalMin.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceTimeIntervalMin.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceTimeIntervalMin.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceTimeIntervalMin.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceTimeIntervalMin.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceTimeIntervalMin.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceTimeIntervalMin.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceTimeIntervalMin.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceTimeIntervalMin.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceTimeIntervalMin.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceTimeIntervalMin.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceTimeIntervalMin.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceTimeIntervalMin.setItemText(23, _translate("Form", "24", None))
        self.cmbSpaceTimeIntervalMax.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceTimeIntervalMax.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceTimeIntervalMax.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceTimeIntervalMax.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceTimeIntervalMax.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceTimeIntervalMax.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceTimeIntervalMax.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceTimeIntervalMax.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceTimeIntervalMax.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceTimeIntervalMax.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceTimeIntervalMax.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceTimeIntervalMax.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceTimeIntervalMax.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceTimeIntervalMax.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceTimeIntervalMax.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceTimeIntervalMax.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceTimeIntervalMax.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceTimeIntervalMax.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceTimeIntervalMax.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceTimeIntervalMax.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceTimeIntervalMax.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceTimeIntervalMax.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceTimeIntervalMax.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceTimeIntervalMax.setItemText(23, _translate("Form", "24", None))
        self.chkSpaceSkipDarkHours.setText(_translate("Form", "Skip dark hours", None))
        self.lblSpaceTimeStep.setText(_translate("Form", "Time Step", None))
        self.cmbSpaceIlluminanceStepType.setItemText(0, _translate("Form", "Hour", None))
        self.cmbSpaceIlluminanceStepType.setItemText(1, _translate("Form", "Day", None))
        self.cmbSpaceIluminanceStepValue.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceIluminanceStepValue.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceIluminanceStepValue.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceIluminanceStepValue.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceIluminanceStepValue.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceIluminanceStepValue.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceIluminanceStepValue.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceIluminanceStepValue.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceIluminanceStepValue.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceIluminanceStepValue.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceIluminanceStepValue.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceIluminanceStepValue.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceIluminanceStepValue.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceIluminanceStepValue.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceIluminanceStepValue.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceIluminanceStepValue.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceIluminanceStepValue.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceIluminanceStepValue.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceIluminanceStepValue.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceIluminanceStepValue.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceIluminanceStepValue.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceIluminanceStepValue.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceIluminanceStepValue.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceIluminanceStepValue.setItemText(23, _translate("Form", "24", None))
        self.cmbSpaceTimeIllum.setToolTip(_translate("Form", "Select a time for which the data is to be displayed.", None))
        self.cmbSpaceTimeIllum.setItemText(0, _translate("Form", "1", None))
        self.cmbSpaceTimeIllum.setItemText(1, _translate("Form", "2", None))
        self.cmbSpaceTimeIllum.setItemText(2, _translate("Form", "3", None))
        self.cmbSpaceTimeIllum.setItemText(3, _translate("Form", "4", None))
        self.cmbSpaceTimeIllum.setItemText(4, _translate("Form", "5", None))
        self.cmbSpaceTimeIllum.setItemText(5, _translate("Form", "6", None))
        self.cmbSpaceTimeIllum.setItemText(6, _translate("Form", "7", None))
        self.cmbSpaceTimeIllum.setItemText(7, _translate("Form", "8", None))
        self.cmbSpaceTimeIllum.setItemText(8, _translate("Form", "9", None))
        self.cmbSpaceTimeIllum.setItemText(9, _translate("Form", "10", None))
        self.cmbSpaceTimeIllum.setItemText(10, _translate("Form", "11", None))
        self.cmbSpaceTimeIllum.setItemText(11, _translate("Form", "12", None))
        self.cmbSpaceTimeIllum.setItemText(12, _translate("Form", "13", None))
        self.cmbSpaceTimeIllum.setItemText(13, _translate("Form", "14", None))
        self.cmbSpaceTimeIllum.setItemText(14, _translate("Form", "15", None))
        self.cmbSpaceTimeIllum.setItemText(15, _translate("Form", "16", None))
        self.cmbSpaceTimeIllum.setItemText(16, _translate("Form", "17", None))
        self.cmbSpaceTimeIllum.setItemText(17, _translate("Form", "18", None))
        self.cmbSpaceTimeIllum.setItemText(18, _translate("Form", "19", None))
        self.cmbSpaceTimeIllum.setItemText(19, _translate("Form", "20", None))
        self.cmbSpaceTimeIllum.setItemText(20, _translate("Form", "21", None))
        self.cmbSpaceTimeIllum.setItemText(21, _translate("Form", "22", None))
        self.cmbSpaceTimeIllum.setItemText(22, _translate("Form", "23", None))
        self.cmbSpaceTimeIllum.setItemText(23, _translate("Form", "24", None))
        self.lblSpaceTime.setText(_translate("Form", "Time", None))
        self.calSpaceDateTimeIllum.setToolTip(_translate("Form", "Select a date by clicking on the calendar. Please note that selecting a year has no bearing on the data being displayed.", None))
        self.calSpaceDateTimeIllum.setDisplayFormat(_translate("Form", "MMMM/d", None))
        self.lblSpaceDate.setText(_translate("Form", "Date", None))
        self.btnSpaceSettingsColours.setText(_translate("Form", "Show Settings", None))
        self.chkSpaceColors.setText(_translate("Form", "Colors", None))
        self.btnSelectColorLowerMask.setText(_translate("Form", "Select Color", None))
        self.lblColorMinLimit.setText(_translate("Form", "Minimum Limit", None))
        self.txtColorsMin.setInputMask(_translate("Form", "000000; ", None))
        self.btnSelectColorUpperMask.setText(_translate("Form", "Select Color", None))
        self.txtColorsMax.setInputMask(_translate("Form", "000000; ", None))
        self.lblColorUpperMask.setText(_translate("Form", "Upper Mask", None))
        self.lblColorMaxLimit.setText(_translate("Form", "Maximum Limit", None))
        self.lblColorLowerMask.setText(_translate("Form", "Lower Mask", None))
        self.txtColorsUpperMask.setInputMask(_translate("Form", "000000; ", None))
        self.txtColorsLowerMask.setInputMask(_translate("Form", "000000; ", None))
        self.cmbSpaceContourQuantity.setItemText(0, _translate("Form", "2", None))
        self.cmbSpaceContourQuantity.setItemText(1, _translate("Form", "3", None))
        self.cmbSpaceContourQuantity.setItemText(2, _translate("Form", "4", None))
        self.cmbSpaceContourQuantity.setItemText(3, _translate("Form", "5", None))
        self.cmbSpaceContourQuantity.setItemText(4, _translate("Form", "6", None))
        self.cmbSpaceContourQuantity.setItemText(5, _translate("Form", "7", None))
        self.btnSpaceResetContours.setText(_translate("Form", "Reset", None))
        self.btnSpaceSetContours.setText(_translate("Form", "Set", None))
        self.chkSpaceAutoFillContours.setToolTip(_translate("Form", "If checked, blank values will be filled through interpolation and extrapolation", None))
        self.chkSpaceAutoFillContours.setText(_translate("Form", "Autofill", None))
        self.cmbSpaceSelectIlluminanceFile.setToolTip(_translate("Form", "<html><head/><body><p>Select the annual illuminance data that is to be plotted. The data selected by default is from the final illuminance file.</p></body></html>", None))
        self.btnSapceSelectFileTypeIlluminance.setToolTip(_translate("Form", "Click to confirm the selection of the annual illuminance time series data.", None))
        self.btnSapceSelectFileTypeIlluminance.setText(_translate("Form", "Confirm", None))
        self.cmbSpacePlotType.setToolTip(_translate("Form", "Select the type of data that you wish to plot", None))
        self.lblSpaceChartOpacity.setText(_translate("Form", "Select Chart Opacity", None))
        self.txtSpaceOpacityValue.setPlaceholderText(_translate("Form", "100", None))
        self.lblSpaceColorSchemeSelect.setText(_translate("Form", "Color Scheme", None))
        self.chkSpaceColorSchemeInvert.setText(_translate("Form", "Invert", None))
        self.btnSpaceSetColorScheme.setText(_translate("Form", "Confirm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpace), _translate("Form", "Space", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTimeSeries), _translate("Form", "Time Series", None))
        self.grpFileDialog.setTitle(_translate("Form", "GroupBox", None))
        self.btnOpenJson.setText(_translate("Form", "Open Json File", None))

